[project]
name = "tiny-mm-gpt"
version = "0.1.0"
description = "Tiny Multi-Modal GPT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["rich>=14.0.0"]

[dependency-groups]
dev = ["ipython>=9.4.0", "pyright>=1.1.402", "ruff>=0.12.2"]

[tool.pyright]
venvPath = "."
venv = ".venv"
